### ISSUE TITLE
Ntex -- use-cases and relation with actix-web

### ISSUE THREAD

**Issue by DarrenBaldwin07** [ntex-rs/ntex#174]
Been messing with Ntex for a few weeks now and really have been enjoying it. The API feels very similar to actix-web -- what are the problems that Ntex attempts to solve and why do they warrant an entirely new framework? Would be curious to hear thoughts.

**Comment by fafhrd91** [comment]
only problem that this framework solves, i use it for my work. i have no intention to solve anyones problems, it might solve some but that is just side effects. this is fork of actix and i am creator of actix. but i think actix is dead, since rust community took actix from me it started to decoy.

in any case this is not an issue, discussion maybe.
